AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-dynamodb
  Sample SAM Template for python-dynamodb
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  DynamoDBLeadsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Environment:
        Variables:
          DYNAMODB_HOST: ""
          DYNAMODB_LOCAL_STAGE: ""
          DYNAMODB_LOCAL_ACCESS_KEY_ID: ""
          DYNAMODB_LOCAL_SECRET_ACCESS_KEY: ""
          DYNAMODB_LOCAL_ENDPOINT: ""
          DYNAMODB_LOCAL_REGION: ""
          STAGE: ""
      Events:
        LeadsPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /leads
            Method: post
        UserStatsPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user_stats
            Method: post
        UserStatsSearchPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user_stats/search
            Method: post
    Metadata:
      DockerTag: python-3.8-function-v1
      DockerContext: ./
      Dockerfile: DockerfileFunction

  DynamoDBLeadsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: leads

  DynamoDBUserStatsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: 'N'
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: user_stats

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DynamoDBLeadsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DynamoDBLeadsFunction.Arn
  DynamoDBLeadsFunctionIamRole:
    Description: "Implicit IAM Role created for DynamoDBLeadsFunction function"
    Value: !GetAtt DynamoDBLeadsFunctionRole.Arn