name: Run npm unit and integration tests for typescript project
on:
  push:
    paths:
      - 'typescript-dynamodb/**'
      - '.github/workflows/typescript_dynamodb_npm_tests.yml'
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd typescript-dynamodb && npm install
      - run: cd typescript-dynamodb && npm test
